version: "3"
services:
  effects:
    # 镜像
    image: nginx:latest
    # 容器名
    container_name: effectsWeb
    # 映射目录
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./html:/data/html
      - ./logs:/var/logs/nginx
    # 端口映射
    ports:
      - "80:80"
    # 重启策略
    restart: always
    # 使用root权限
    privileged: true
    # 环境变量
    # environment:
    # 使用桥接网络
    network_mode: "bridge"
